server:
  port: "8080"

mode:
  develop: true

db:
  dsn: root:yourpassword@(127.0.0.1:3306)/hi-dreamai?charset=utf8mb4&parseTime=True&loc=Local
  SetMaxIdleConn: 10 # 最多空闲连接数
  SetMaxOpenConn: 10 # 最多打开连接数

log:
  MaxSize: 1 # 日志文件最大尺寸（M），超限后自动分割
  MaxBackups: 10 # 保存旧文件的最大个数
  MaxAge: 90 # 保存旧文件的最大天数